
export const ADD_POKEMON_DETAIL = 'ADD_POKEMON_DETAIL';
export const FILTER_DB = 'FILTER_DB';
export const FILTER_TYPE = 'FILTER_TYPE';
export const GET_ALLPOKEMON = 'GET_ALLPOKEMON';
export const GET_POKEMON_NAME = 'GET_POKEMON_NAME';
export const GET_POKEMON_TYPES = 'GET_POKEMON_TYPES';
export const ORDER_ATAQUEPOKE = 'ORDER_ATAQUE';
export const ORDER_NAMEPOKE = 'ORDER_NAME';
export const POST_POKEMON = 'POST_POKEMON';
export const RESET_DETAIL = 'RESET_DETAIL';